"""Добавил источник , переименовал сессион

Revision ID: 81ee19c6879a
Revises: 9f40e6ae16fb
Create Date: 2024-09-02 23:52:10.396747

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '81ee19c6879a'
down_revision: Union[str, None] = '9f40e6ae16fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('segment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_with_rate_1', sa.Integer(), nullable=True),
    sa.Column('post_with_rate_2', sa.Integer(), nullable=True),
    sa.Column('post_with_rate_3', sa.Integer(), nullable=True),
    sa.Column('post_with_rate_4', sa.Integer(), nullable=True),
    sa.Column('post_with_rate_5', sa.Integer(), nullable=True),
    sa.Column('post_with_rate_6', sa.Integer(), nullable=True),
    sa.Column('post_with_rate_7', sa.Integer(), nullable=True),
    sa.Column('post_with_rate_8', sa.Integer(), nullable=True),
    sa.Column('post_with_rate_9', sa.Integer(), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['post_with_rate_1'], ['post.id'], name=op.f('fk_segment_post_with_rate_1_post')),
    sa.ForeignKeyConstraint(['post_with_rate_2'], ['post.id'], name=op.f('fk_segment_post_with_rate_2_post')),
    sa.ForeignKeyConstraint(['post_with_rate_3'], ['post.id'], name=op.f('fk_segment_post_with_rate_3_post')),
    sa.ForeignKeyConstraint(['post_with_rate_4'], ['post.id'], name=op.f('fk_segment_post_with_rate_4_post')),
    sa.ForeignKeyConstraint(['post_with_rate_5'], ['post.id'], name=op.f('fk_segment_post_with_rate_5_post')),
    sa.ForeignKeyConstraint(['post_with_rate_6'], ['post.id'], name=op.f('fk_segment_post_with_rate_6_post')),
    sa.ForeignKeyConstraint(['post_with_rate_7'], ['post.id'], name=op.f('fk_segment_post_with_rate_7_post')),
    sa.ForeignKeyConstraint(['post_with_rate_8'], ['post.id'], name=op.f('fk_segment_post_with_rate_8_post')),
    sa.ForeignKeyConstraint(['post_with_rate_9'], ['post.id'], name=op.f('fk_segment_post_with_rate_9_post')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_segment'))
    )
    op.drop_table('session')
    op.add_column('post', sa.Column('source', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'source')
    op.create_table('session',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('post_with_rate_1', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('post_with_rate_2', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('post_with_rate_3', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('post_with_rate_4', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('post_with_rate_5', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('post_with_rate_6', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('post_with_rate_7', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('post_with_rate_8', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('post_with_rate_9', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_on', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['post_with_rate_1'], ['post.id'], name='fk_session_post_with_rate_1_post'),
    sa.ForeignKeyConstraint(['post_with_rate_2'], ['post.id'], name='fk_session_post_with_rate_2_post'),
    sa.ForeignKeyConstraint(['post_with_rate_3'], ['post.id'], name='fk_session_post_with_rate_3_post'),
    sa.ForeignKeyConstraint(['post_with_rate_4'], ['post.id'], name='fk_session_post_with_rate_4_post'),
    sa.ForeignKeyConstraint(['post_with_rate_5'], ['post.id'], name='fk_session_post_with_rate_5_post'),
    sa.ForeignKeyConstraint(['post_with_rate_6'], ['post.id'], name='fk_session_post_with_rate_6_post'),
    sa.ForeignKeyConstraint(['post_with_rate_7'], ['post.id'], name='fk_session_post_with_rate_7_post'),
    sa.ForeignKeyConstraint(['post_with_rate_8'], ['post.id'], name='fk_session_post_with_rate_8_post'),
    sa.ForeignKeyConstraint(['post_with_rate_9'], ['post.id'], name='fk_session_post_with_rate_9_post'),
    sa.PrimaryKeyConstraint('id', name='pk_session')
    )
    op.drop_table('segment')
    # ### end Alembic commands ###
