"""Первое сохранение

Revision ID: 9f40e6ae16fb
Revises: 
Create Date: 2024-09-01 23:40:33.543003

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f40e6ae16fb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=False),
    sa.Column('rate', sa.Integer(), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_post'))
    )
    op.create_table('session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_with_rate_1', sa.Integer(), nullable=True),
    sa.Column('post_with_rate_2', sa.Integer(), nullable=True),
    sa.Column('post_with_rate_3', sa.Integer(), nullable=True),
    sa.Column('post_with_rate_4', sa.Integer(), nullable=True),
    sa.Column('post_with_rate_5', sa.Integer(), nullable=True),
    sa.Column('post_with_rate_6', sa.Integer(), nullable=True),
    sa.Column('post_with_rate_7', sa.Integer(), nullable=True),
    sa.Column('post_with_rate_8', sa.Integer(), nullable=True),
    sa.Column('post_with_rate_9', sa.Integer(), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['post_with_rate_1'], ['post.id'], name=op.f('fk_session_post_with_rate_1_post')),
    sa.ForeignKeyConstraint(['post_with_rate_2'], ['post.id'], name=op.f('fk_session_post_with_rate_2_post')),
    sa.ForeignKeyConstraint(['post_with_rate_3'], ['post.id'], name=op.f('fk_session_post_with_rate_3_post')),
    sa.ForeignKeyConstraint(['post_with_rate_4'], ['post.id'], name=op.f('fk_session_post_with_rate_4_post')),
    sa.ForeignKeyConstraint(['post_with_rate_5'], ['post.id'], name=op.f('fk_session_post_with_rate_5_post')),
    sa.ForeignKeyConstraint(['post_with_rate_6'], ['post.id'], name=op.f('fk_session_post_with_rate_6_post')),
    sa.ForeignKeyConstraint(['post_with_rate_7'], ['post.id'], name=op.f('fk_session_post_with_rate_7_post')),
    sa.ForeignKeyConstraint(['post_with_rate_8'], ['post.id'], name=op.f('fk_session_post_with_rate_8_post')),
    sa.ForeignKeyConstraint(['post_with_rate_9'], ['post.id'], name=op.f('fk_session_post_with_rate_9_post')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_session'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('session')
    op.drop_table('post')
    # ### end Alembic commands ###
